server:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 3218818005g@gmail.com
    password: pcjyzglqwvvodgdf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: false
  port: 9999
  servlet:
    context-path: /boot-design

logging:
  level:
    com.baomidou.mybatisplus.core: debug
    com.intern.design: debug


spring:
  application:
    name: boot-design

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password:
