server:

  port: 9999
  servlet:
    context-path: /boot-design

logging:
  level:
    com.baomidou.mybatisplus.core: debug
    com.intern.design: debug


spring:
  application:
    name: boot-design

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 465
    username: 3218818005g@gmail.com
    password: ekspzkcyokquegnq   # ← 去掉空格的16位
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.debug: true           # 临时开调试日志，定位更方便；OK后可关
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(1-已删除 0-未删除)
      column-format: "`%s`"


minio:
  access-key: admin
  secret-key: password
  url: http://localhost:9001
  bucket-name: export-files